steps:
  publish-nextcloud-upload:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: ellpeck/woodpecker-nextcloud-upload
      dockerfile: nextcloud-upload/Dockerfile
      platforms: windows/amd64,darwin/amd64,darwin/arm64,freebsd/amd64,linux/amd64,linux/arm64/v8
      tags: latest,$CI_COMMIT_SHA
    when:
      branch: main
      event: push
      path: "nextcloud-upload"
