steps:
  publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: ellpeck/woodpecker-nextcloud-upload
      dockerfile: nextcloud-upload/Dockerfile
      platforms: linux/amd64, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/riscv64
      tags: latest, ${CI_COMMIT_SHA}
      username: ellpeck
      password:
        from_secret: docker_token
    when:
      branch: main
      event: push
      path: "nextcloud-upload/*"
